name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
    - name: Set env value for tarpaulin
      id: step_one
      run: |
       echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
    - name: rust-tarpaulin
      uses: actions-rs/tarpaulin@v0.1.0
      with:
        args: --ignore-tests
    - name: rust-clippy-check
      uses: actions-rs/clippy-check@v1.0.7
      with:
        args: -- -D warnings
    - name: Check formatting of Rust code with rustfmt
      uses: actions-rust-lang/rustfmt@v1.0.0
    - name: rust-audit-check
      uses: actions-rs/audit-check@v1.2.0
      with: 
        token: ${{ github.token }}
